# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.4.x version
  - 5.4

mysql:
 database: drupal
 username: root
 encoding: utf8

install:

 - sudo apt-get update > /dev/null
 - "mysql -e 'create database drupal;'"

 # Install latest Drush 6.
 - export PATH="$HOME/.composer/vendor/bin:$PATH"
 - composer global require --no-interaction --prefer-source drush/drush:6.*
 - drush dl -y drupalorg_drush-7.x-1.x-dev --destination=$HOME/.drush
 - drush cc drush

 # Build Codebase
 - cd ..
 - mkdir private_files
 - mkdir profiles
 - mv mz profiles/
 - mkdir drupal
 - mv profiles drupal/

 # Build the current branch
 - cd drupal
 - drush make --yes profiles/mz/drupal-org-core.make --prepare-install
 - drush make --yes profiles/mz/mz.make --no-core --contrib-destination=profiles/mz
 - cd ../

 # Setup files
 - sudo chmod -R 777 drupal/sites/all

 # Disable sendmail
 - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
 # Do the site install
 - cd drupal
 - drush site-install mz --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="MZ" --yes

script:
 # Enable migrate and test migrate examples
 - drush en migrate,mz_migrate_example -y
 - drush mreg
 - drush mi --group=mz_example

notifications:
 flowdock: 5c81bb34f6ca9c86da0d32d92596a3db
